# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Lambda Layers For New Node.js Releases

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Check for new Node.js releases and build new layers
      run: |
        npm i -g zx
        npm ci
        npm test
